apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: app-volume
        emptyDir: {}
      containers:
      - name: tomcat
        image: tomcat:jre25-temurin-noble
        volumeMounts:
        - name: app-volume
          mountPath: /data
