apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-apps
  template:
    metadata:
      labels:
        app: my-apps
    spec:
      containers:
        - name: nginx1
          image: nginx
          env:
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_MODE
            - name: DB_PASSWORD
               valueFrom:
                 secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          command: ["sh", "-c"]
          args:
            - echo "Hello from deployment, APP_MODE=$APP_MODE" && sleep infinity
